Updated for 12 week
lighthouse-labs/web-js-palindromes pull request #1
Opened 2019-07-04 18:40 UTC by notadeejay

var => const

2019-07-04 21:55 UTC, kvirani requested changes

2019-07-04 21:55 UTC, kvirani commented on lib/palindromes.js
>  }
missing semicolon.

2019-07-04 21:56 UTC, kvirani requested changes
this time as a suggested edit (new feature in github im not that used to)

2019-07-04 21:56 UTC, kvirani commented on lib/palindromes.js
>  }
```suggestion
};
```

2019-07-05 13:09 UTC, notadeejay commented on lib/palindromes.js
>  }
ooooh neat

2019-07-05 16:42 UTC, merged